Repository Wr-40Java/back-end-app, pull requests merged in 2022-12, with the labels that each got.

#79 update -- InsurenceCompany without relationships . Closes #78
  src/main/java/Wr40/cardiary/controller/InsuranceController.java
  src/main/java/Wr40/cardiary/service/InsuranceService.java
  src/test/java/Wr40/cardiary/service/InsuranceServiceTest.java
Labels: enhancement, Back-end, CRUD

#74 Implementation of CRUD and tests for Tax
  src/main/java/Wr40/cardiary/controller/TaxController.java
  src/main/java/Wr40/cardiary/exception/TaxNotFoundException.java
  src/main/java/Wr40/cardiary/model/dto/TaxDTO.java
  src/main/java/Wr40/cardiary/model/entity/Tax.java
  src/main/java/Wr40/cardiary/repo/TaxRepository.java
  src/main/java/Wr40/cardiary/service/TaxService.java
  src/test/java/Wr40/cardiary/controller/TaxControllerTest.java
  src/test/java/Wr40/cardiary/test/model/TestTaxDTO.java
  src/test/java/Wr40/cardiary/test/service/TaxServiceTest.java
Labels: Epic, Back-end, CRUD

#134 120 add taxtype to tax implementation
  src/main/java/Wr40/cardiary/controller/TaxController.java
  src/main/java/Wr40/cardiary/service/TaxService.java
  src/test/java/Wr40/cardiary/service/TaxServiceTest.java
Labels: enhancement, Back-end

#148 123 technical service delete technical service implementation
  src/main/java/Wr40/cardiary/controller/TechnicalServiceController.java
  src/main/java/Wr40/cardiary/exception/UnableToDeleteTechnicalServiceException.java
  src/main/java/Wr40/cardiary/service/TechnicalServiceService.java
  src/main/resources/application.properties
  src/test/java/Wr40/cardiary/service/TechnicalServiceServiceTest.java
Labels: enhancement, Back-end, CRUD

#126 statistics - maintenance event history (tested)
  src/main/java/Wr40/cardiary/controller/StatisticsController.java
  src/main/java/Wr40/cardiary/model/dto/MaintenanceEventDTO.java
  src/main/java/Wr40/cardiary/model/dto/MaintenanceHistoryDTO.java
  src/main/java/Wr40/cardiary/model/dto/statistics/AvgMaintenanceStatsDTO.java
  src/main/java/Wr40/cardiary/model/dto/statistics/MaintenanceStatisticsDTO.java
  src/main/java/Wr40/cardiary/model/dto/statistics/SumMaintenanceStatsDTO.java
  src/main/java/Wr40/cardiary/model/entity/MaintenanceEvent.java
  src/main/java/Wr40/cardiary/model/entity/MaintenanceHistory.java
  src/main/java/Wr40/cardiary/repo/MaintenanceEventRepository.java
  src/main/java/Wr40/cardiary/repo/MaintenanceHistoryRepository.java
  src/main/java/Wr40/cardiary/service/StatisticsService.java
  src/main/resources/application.properties
  src/test/java/Wr40/cardiary/service/InsuranceServiceTest.java
  src/test/java/Wr40/cardiary/service/StatisticsServiceTest.java
Labels: enhancement, Back-end, Statistics
